---
title: "Precision and recall in WGCNA networks using canonical pathway databases with RIN as the known covariate"
output:
  html_document:
    code_folding: hide
---


This script generates panels for figure 2 and supplementary figure 1a-b in the manuscript titled -- "Addressing confounding artifacts in reconstruction of gene co-expression networks"

```{r}
rm(list = ls())

source("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/src/config")
library(igraph)

## function to compute precision and recall
plot_precision_recall <- function(tissuename, truep.falsen, genes.network.index, gene.symbols.innetwork ){
  fn <- tissuename
  # fn <- "Subcutaneous"

  version.data <- c(pcglasso, half.pcglasso, quarter.pcglasso, exonic.glasso, expeff.glasso, ringlasso, gcglasso, rawglasso)
  ## for each dataset
        precision <- matrix(ncol = length(version.data), nrow = 50)
        recall <- matrix(ncol = length(version.data), nrow = 50)

  for(j in 1:length(version.data)){
    # j = 3
    ## load dataset
    load(paste(version.data[j], fn, ".Rdata", sep = ""))
    glasso.network <- lapply(glasso.network, f <- function(m) {
        m[lower.tri(m)] <- t(m)[lower.tri(m)]
        m
    }
    )
    glasso.network <- lapply(glasso.network, function(x,y,z){
      x <- x[z,z]
      x[which(is.na(x))] <- 0
      dimnames(x) <- list(y,y)
      x
      }, gene.symbols.innetwork, genes.network.index)

    precision.recall <- sapply(glasso.network, function(x,y){
      x <- graph_from_adjacency_matrix(x, mode = "undirected", diag = F, weighted = T)
      tp <- ecount(graph.intersection(x,y))
      fp <- ecount(graph.difference(x,y))
      fn <- ecount(y) - tp
      precision.infunc <- tp/(tp+fp)
      recall.infunc <- tp/(tp+fn)
      return(c(precision.infunc, recall.infunc))
      }, truep.falsen)

    precision[,j] <- precision.recall[1,]
    recall[,j] <- precision.recall[2,]
  }

  colnames(precision) <- c("PC corrected","half-PC","quarter-PC", "exonic rate", "expeff", "RIN", "gene GC%", "uncorrected")
  rownames(precision) <- lambda
  plot.precision <- melt(precision)

  colnames(recall) <- c("PC corrected","half-PC","quarter-PC", "exonic rate", "expeff", "RIN", "gene GC%", "uncorrected")
  rownames(recall) <- lambda
  plot.recall <- melt(recall)
  plot.both <- cbind(plot.precision, plot.recall[,3])
  colnames(plot.both) <- c("lambda", "type", "precision", "recall")
  plot.both
}

## process the total list of true positives and false negatives --> total gene-gene pairs from the genesets
## read genesets of interest
g.sets <- read.delim("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/data/genesets/canonical_pathways_merged.txt", header = F, stringsAsFactors = F, row.names = 1)
g.sets$V2 <- NULL
names.gsets <- rownames(g.sets)
g.sets <- t(g.sets)
g.sets <- sapply(g.sets, function(x) strsplit(x,',')[[1]])
names(g.sets) <- names.gsets
g.sets <- lapply(g.sets, sort)
all.genes.inset <- unlist(g.sets)
names(all.genes.inset) <- NULL
g.sets <- lapply(g.sets, function(x){
  g <- make_full_graph(length(x))
  V(g)$name <- x
  get.edgelist(g)
  })
g.sets <- do.call(rbind, g.sets)
g.sets <- unique(data.frame(g.sets))
tp.fn <- graph.data.frame(g.sets, directed = FALSE)

## get gene names
    # PC corrected
    load("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/data/gtex_half_pc_corrected.Rdata")
    ###**** REMEMBER 1 is hard coded in the next line ****###
    pc.gene.symbols <- sapply(rowData(gtex.half.pc.corrected[[1]])$symbol, function(x) x[[1]][1])
    genes.network.withnames <- which(!is.na(pc.gene.symbols))
    pc.gene.symbols <- pc.gene.symbols[genes.network.withnames]

    ## count overlapping genesets
    missing.genes <- all.genes.inset[which(!all.genes.inset %in% pc.gene.symbols)]
    tp.fn <- delete_vertices(tp.fn, missing.genes)
    count.tp.fn <- ecount(tp.fn)
    
#### Run function
plot.thyroid <- plot_precision_recall("Thyroid", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.thyroid, "pr_table_thyroid.csv")


plot.muscle <- plot_precision_recall("Muscle", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.muscle, "pr_table_muscle.csv")


plot.lung <- plot_precision_recall("Lung", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.lung, "pr_table_lung.csv")

plot.blood <- plot_precision_recall("Blood", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.blood, "pr_table_blood.csv")

plot.sub <- plot_precision_recall("Subcutaneous", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.sub, "pr_table_sub.csv")

```

```{r}
source("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/src/config")
library(cowplot)

## Read files
theme_set(theme_cowplot(font_size=12)) # reduce default font size

wgcna.plot.muscle <- read.csv("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/publication_figures/fig2/pr_table_muscle.csv", 
  row.names = 1, stringsAsFactors = F)
wgcna.plot.muscle <- wgcna.plot.muscle[-which(wgcna.plot.muscle$type %in% c("exonic rate","expeff", "gene GC%")),]
wgcna.plot.muscle$type <- factor(wgcna.plot.muscle$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
wgcna.plot.muscle <- ggplot(wgcna.plot.muscle, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Muscle - Skeletal")

wgcna.plot.blood <- read.csv("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/publication_figures/fig2/pr_table_blood.csv", 
  row.names = 1, stringsAsFactors = F)
wgcna.plot.blood <- wgcna.plot.blood[-which(wgcna.plot.blood$type %in% c("exonic rate", "expeff", "gene GC%")),]
wgcna.plot.blood$type <- factor(wgcna.plot.blood$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
wgcna.plot.blood <- ggplot(wgcna.plot.blood, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Whole Blood")

glasso.plot.muscle <- read.csv("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/publication_figures/fig3/pr_table_muscle.csv", 
  row.names = 1, stringsAsFactors = F)
glasso.plot.muscle <- glasso.plot.muscle[-which(glasso.plot.muscle$type %in% c("exonic rate","expeff", "gene GC%")),]
glasso.plot.muscle$type <- factor(glasso.plot.muscle$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
glasso.plot.muscle <- ggplot(glasso.plot.muscle, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Muscle-Skeletal")

glasso.plot.blood <- read.csv("/home-3/pparsan1@jhu.edu/work2/princy/claire_network/Network-Inference/gtex_networks/publication_figures/fig3/pr_table_blood.csv", 
  row.names = 1, stringsAsFactors = F)
glasso.plot.blood <- glasso.plot.blood[-which(glasso.plot.blood$type %in% c("exonic rate", "expeff", "gene GC%")),]
glasso.plot.blood$type <- factor(glasso.plot.blood$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
glasso.plot.blood <- ggplot(glasso.plot.blood, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3)+
         xlab("Recall") + ylab("Precision")+ggtitle("Whole Blood") 

supp.fig.p1 <- plot_grid(wgcna.plot.blood + xlim(0,0.13) + ylim(0, 0.35) + theme(legend.position="none"),
  wgcna.plot.muscle + xlim(0,0.13) + ylim(0, 0.35) +  theme(legend.position="none"),
  align = 'vh',
           labels = c("a", "b"),
           hjust = -1,
           nrow = 1
           )
wgcna.legend <- get_legend(wgcna.plot.blood +
  theme(legend.key = element_rect(color = "black", linetype = "solid", size = 0.5),
  legend.key.size = unit(0.3, "cm"), legend.key.height=unit(1.5,"line")) + 
  guides(colour = guide_legend(override.aes = list(size= 1))))

supp.fig.p1 <- plot_grid( supp.fig.p1, wgcna.legend, rel_widths = c(3, .4))

supp.fig.p2 <- plot_grid(glasso.plot.blood + xlim(0,0.013) + ylim(0, 0.7) + theme(legend.position="none"),
  glasso.plot.muscle + xlim(0,0.013) + ylim(0, 0.7) +  theme(legend.position="none"),
  align = 'vh',
           labels = c("c", "d"),
           hjust = -1,
           nrow = 1
           )
glasso.legend <- get_legend(glasso.plot.muscle +
  theme(legend.key = element_rect(color = "black", linetype = "solid", size = 0.5),
  legend.key.size = unit(0.3, "cm"), legend.key.height=unit(1.5,"line")) + 
  guides(colour = guide_legend(override.aes = list(size= 1))))


supp.fig.p2 <- plot_grid( supp.fig.p2, glasso.legend, rel_widths = c(3, .4))
plot_grid(supp.fig.p1, supp.fig.p2, nrow = 2)
```
