---
title: "WGCNA - # genes assigned to a module (non-gray) by tissue"
output: html_notebook
---

```{r "setup", include=FALSE}
require("knitr")
opts_knit$set(root.dir = "/work-zfs/abattle4/parsana/networks_correction/networks/")
```

```{r}
rm(list = ls())
library(reshape2)
library(ggplot2)
load("raw/wgcna_networks.Rdata")
tiss <- "Thyroid"
raw <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("rin/wgcna_networks.Rdata")
rin <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("quarterpc/wgcna_networks.Rdata")
quarterPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("halfpc//wgcna_networks.Rdata")
halfPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("pc//wgcna_networks.Rdata")
pc <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

plot.mod <- melt(cbind(raw, rin, quarterPC, halfPC, pc))
plot.mod$Var2 <- factor(plot.mod$Var2, levels = c("pc", "halfPC", "quarterPC", "rin", "raw"), labels = c("PC", "half-PC", "quarter-PC", "RIN", "uncorrected"))

ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle(tiss)+
  xlab("cut-height") + ylab("# genes assigned to modules")
```

```{r}
tiss <- "Subcutaneous"
load("raw/wgcna_networks.Rdata")
raw <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("rin/wgcna_networks.Rdata")
rin <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("quarterpc/wgcna_networks.Rdata")
quarterPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("halfpc//wgcna_networks.Rdata")
halfPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("pc//wgcna_networks.Rdata")
pc <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

plot.mod <- melt(cbind(raw, rin, quarterPC, halfPC, pc))
plot.mod$Var2 <- factor(plot.mod$Var2, levels = c("pc", "halfPC", "quarterPC", "rin", "raw"), labels = c("PC", "half-PC", "quarter-PC", "RIN", "uncorrected"))

ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle(tiss)+
  xlab("cut-height") + ylab("# genes assigned to modules")
```

```{r}
tiss <- "Lung"
load("raw/wgcna_networks.Rdata")
raw <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("rin/wgcna_networks.Rdata")
rin <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("quarterpc/wgcna_networks.Rdata")
quarterPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("halfpc//wgcna_networks.Rdata")
halfPC <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

load("pc//wgcna_networks.Rdata")
pc <- sapply(dat.net[[tiss]], function(x) length(which(x$colors!=0)))

plot.mod <- melt(cbind(raw, rin, quarterPC, halfPC, pc))
plot.mod$Var2 <- factor(plot.mod$Var2, levels = c("pc", "halfPC", "quarterPC", "rin", "raw"), labels = c("PC", "half-PC", "quarter-PC", "RIN", "uncorrected"))

ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle(tiss)+
  xlab("cut-height") + ylab("# genes assigned to modules")
```

