---
title: "WGCNA module distribution"
output: html_notebook
---

```{r "setup", include=FALSE}
require("knitr")
opts_knit$set(root.dir = "/work-zfs/abattle4/parsana/networks_correction_v/networks/")
```

```{r}
rm(list = ls())
library(reshape2)
library(ggplot2)
load("raw/wgcna_networks.Rdata")
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- melt(do.call(cbind, plot.mod))
ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle("Raw")+
  xlab("cut-height") + ylab("# modules")
```

```{r}
load("rin/wgcna_networks.Rdata")
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- melt(do.call(cbind, plot.mod))
ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle("RIN")+
  xlab("cut-height") + ylab("# modules")
```

```{r}
load("quarterpc/wgcna_networks.Rdata")
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- melt(do.call(cbind, plot.mod))
ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle("quarter-PC")+
  xlab("cut-height") + ylab("# modules")
```

```{r}
load("halfpc//wgcna_networks.Rdata")
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- melt(do.call(cbind, plot.mod))
ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle("halfPC")+
  xlab("cut-height") + ylab("# modules")
```

```{r}
load("pc//wgcna_networks.Rdata")
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- lapply(dat.net, function(y) sapply(y, function(x) length(unique(x$colors))-1))
plot.mod <- melt(do.call(cbind, plot.mod))
ggplot(plot.mod, aes(x = Var1, y = value, col = Var2)) + geom_point()+ggtitle("PC")+
  xlab("cut-height") + ylab("# modules")
```
