---
title: "Thyroid alternate correction"
output: html_notebook
---

```{r}
rm(list = ls())
tiss <- "Thyroid"
load("../data/raw_subset.Rdata")
load("../data/pc_loadings.Rdata")

dat.expr <- dat.expr[[tiss]]
pc.loadings <- pc.loadings[[tiss]]
num.pc.estimates <- num.pc.estimates[[tiss]]
```
## correct thyroid data with top 38 PCs, except PC2 -- i.e. total of 37 PCs
```{r}
pc.loadings <- pc.loadings[,1:num.pc.estimates]
pc.loadings <- pc.loadings[,-2]
dat.corrected <- lm(t(dat.expr@assays$data$counts) ~ pc.loadings)$residuals
SummarizedExperiment::assay(dat.expr, 1) <- t(dat.corrected)
save(dat.expr, file = "../data/thyroid_pc_corrected_withPC2.Rdata")
```

## Run WGCNA with the highest cutheight
```{r}
rm(list = ls())
source("../src/functions.R")
source("../src/config.R")
load("../data/thyroid_pc_corrected_withPC2.Rdata")
dat.expr <- normalize(dat.expr)
cutheights <- cutheights[49]
type.tom <- "unsigned"

dat <- t(assay(dat.expr, 1)) ## genes in columns for WGCNA
power.value <- pick.power(dat, nType = type.tom)
print(power.value)
```

```{r}
# Learn wgcna network with PC2 left in
dat.net.pc2 <- blockwiseModules(dat, power = power.value,TOMType = type.tom, saveTOMs = FALSE,
                                minModuleSize = minModuleSize, networkType = type.tom,
                                reassignThreshold = reassignThreshold, 
                                detectCutHeight = cutheights, 
                                mergeCutHeight = 0.20,
                                numericLabels = TRUE, 
                                pamRespectsDendro = FALSE,
                                verbose = 3)
modules.pc2 <- dat.net.pc2$colors
names(modules.pc2) <- colnames(dat)
save(dat.net.pc2, file = "../networks/wgcna_thyroid_withpc2.Rds")
```

## Map ensembl ids to entrez id
```{r}
rm(list = ls())
load("../data/thyroid_pc_corrected_withPC2.Rdata")
library(org.Hs.eg.db)
myenslist <- sapply(rownames(dat.expr), function(x) strsplit(x, "\\.")[[1]][1])
myentrezid <- sapply(myenslist, function(x) exists(x, org.Hs.egENSEMBL2EG))

ens <- unlist(as.list(org.Hs.egENSEMBL2EG))
myens2entrez <- ens[myenslist]
names(myens2entrez) <- myenslist

```
```{r}
# load raw and pc corrected wgcna
load("../networks/raw/wgcna_networks.Rdata")
dat.net.raw <- dat.net[["Thyroid"]][[49]]
modules.raw <- dat.net.raw$colors
load("../networks/pc/wgcna_networks.Rdata")
dat.net.PC <- dat.net[["Thyroid"]][[49]]
modules.PC <- dat.net.PC$colors

load("../networks/wgcna_thyroid_withpc2.Rds")
```
```{r}
## RAW
## remove gray modules for each
gray.raw <- which(modules.raw == 0)
modules.raw <- modules.raw[-gray.raw]
myens2entrez.raw <- myens2entrez[-gray.raw]
## Enrichment for raw
enrich.raw <- GOenrichmentAnalysis(modules.raw, myens2entrez.raw, evidence = "all", organism = "human")

```
```{r}
## PC2
modules.pc2 <- dat.net.pc2$colors
gray.pc2 <- which(modules.pc2 == 0)
modules.pc2 <- modules.pc2[-gray.pc2]
myens2entrez.pc2 <- myens2entrez[-gray.pc2]

enrich.pc2 <- GOenrichmentAnalysis(modules.pc2, myens2entrez.pc2, evidence = "all", organism = "human")

## PC
gray.pc <- which(modules.PC == 0)
modules.PC <- modules.PC[-gray.pc]
myens2entrez.pc <- myens2entrez[-gray.pc]

enrich.pc <- GOenrichmentAnalysis(modules.PC, myens2entrez.pc, evidence = "all", organism = "human")

raw.enrich <- enrich.raw$bestPTerms$`BP, CC, MF`$enrichment
pc2.enrich <- enrich.pc2$bestPTerms$`BP, CC, MF`$enrichment
pc.enrich <- enrich.pc$bestPTerms$`BP, CC, MF`$enrichment
save(raw.enrich, pc2.enrich, pc.enrich, file = "enrichment_wgcna_raw_pc_pc2.Rdata")
write.csv(raw.enrich, file = "raw_enrich.csv")
write.csv(pc2.enrich, file = "pc2.enrich.csv")
write.csv(pc.enrich, file = "pc.enrich.csv")
```

