---
title: "Precision and recall in WGCNA networks using canonical pathway databases with RIN as the known covariate"
output:
  html_document:
    code_folding: hide
---


This script generates panels for figure 2 and supplementary figure 1a-b in the manuscript titled -- "Addressing confounding artifacts in reconstruction of gene co-expression networks"

```{r}
rm(list = ls())

source("/work-zfs/abattle4/parsana/networks_correction/src/config")
library(igraph)

## function to compute precision and recall
plot_precision_recall <- function(tissuename, truep.falsen, genes.network.index, gene.symbols.innetwork ){
  fn <- tissuename
  # fn <- "Subcutaneous"
  version.data <- c(pc, half.pc, quarter.pc, exonic, expeff, rin, gc, raw)
  ## for each dataset
        precision <- matrix(ncol = length(version.data), nrow = 50)
        recall <- matrix(ncol = length(version.data), nrow = 50)
  for(j in 1:length(version.data)){
    load(paste(version.data[j],"wgcna_networks.RData", sep = ""))
    wgcna.networks <- wgcna.networks[[fn]]
    modules.genes <- vector("list",length=length(wgcna.networks))
    networks.list <- vector("list",length=length(wgcna.networks))
    # tp.fp <- vector("numeric", length = length(wgcna.networks))
    for(i in 1:length(wgcna.networks)){
      modules.genes[[i]] <- sapply(sort(unique(wgcna.networks[[i]]$colors))[-1], function(x,y,z,q){
        y.withgenenames <- y$colors[z]
        q[which(y.withgenenames == x)]
          }, wgcna.networks[[i]], genes.network.index, gene.symbols.innetwork)

      ## convert modules to fully connected graph
      networks.list[[i]] <- lapply(modules.genes[[i]], function(x){
      g <- make_full_graph(length(x))
      V(g)$name <- x
      get.edgelist(g)
      })

      networks.list[[i]] <- do.call(rbind, networks.list[[i]])
      networks.list[[i]] <- unique(data.frame(networks.list[[i]]))
      networks.list[[i]] <- graph.data.frame(networks.list[[i]], directed = FALSE)
      # rm(networks.list)
    }
    
    precision.recall <- sapply(networks.list, function(x,y){
      tp <- ecount(graph.intersection(x,y))
      fp <- ecount(graph.difference(x,y))
      fn <- ecount(y) - tp
      precision.infunc <- tp/(tp+fp)
      recall.infunc <- tp/(tp+fn)
      return(c(precision.infunc, recall.infunc))
      }, truep.falsen)

    precision[,j] <- precision.recall[1,]
    recall[,j] <- precision.recall[2,]
  }
  colnames(precision) <- c("PC corrected","half-PC","quarter-PC", "RIN", "gene GC%", "uncorrected")
  rownames(precision) <- cutheights
  plot.precision <- melt(precision)

  colnames(recall) <- c("PC corrected","half-PC","quarter-PC", "RIN", "gene GC%", "uncorrected")
  rownames(recall) <- cutheights
  plot.recall <- melt(recall)

  plot.both <- cbind(plot.precision, plot.recall[,3])
  colnames(plot.both) <- c("Cutheights", "type", "precision", "recall")
  plot.both
}

## process the total list of true positives and false negatives --> total gene-gene pairs from the genesets
## read genesets of interest
g.sets <- read.delim("/work-zfs/abattle4/parsana/networks_correction/data/genesets/canonical_pathways_merged.txt", header = F, stringsAsFactors = F, row.names = 1)
g.sets$V2 <- NULL
names.gsets <- rownames(g.sets)
g.sets <- t(g.sets)
g.sets <- sapply(g.sets, function(x) strsplit(x,',')[[1]])
names(g.sets) <- names.gsets
g.sets <- lapply(g.sets, sort)
all.genes.inset <- unlist(g.sets)
names(all.genes.inset) <- NULL
g.sets <- lapply(g.sets, function(x){
  g <- make_full_graph(length(x))
  V(g)$name <- x
  get.edgelist(g)
  })
g.sets <- do.call(rbind, g.sets)
g.sets <- unique(data.frame(g.sets))
tp.fn <- graph.data.frame(g.sets, directed = FALSE)

## get gene names
    # PC corrected
    load("/work-zfs/abattle4/parsana/networks_correction/data/gtex_half_pc_corrected.Rdata")
    ###**** REMEMBER 1 is hard coded in the next line ****###
    pc.gene.symbols <- sapply(rowData(gtex.half.pc.corrected[[1]])$symbol, function(x) x[[1]][1])
    genes.network.withnames <- which(!is.na(pc.gene.symbols))
    pc.gene.symbols <- pc.gene.symbols[genes.network.withnames]

    ## count overlapping genesets
    missing.genes <- all.genes.inset[which(!all.genes.inset %in% pc.gene.symbols)]
    tp.fn <- delete_vertices(tp.fn, missing.genes)
    count.tp.fn <- ecount(tp.fn)
    


#### Run function
plot.thyroid <- plot_precision_recall("Thyroid", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.thyroid, "pr_table_thyroid.csv")


plot.muscle <- plot_precision_recall("Muscle", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.muscle, "pr_table_muscle.csv")


plot.lung <- plot_precision_recall("Lung", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.lung, "pr_table_lung.csv")

plot.blood <- plot_precision_recall("Blood", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.blood, "pr_table_blood.csv")

plot.sub <- plot_precision_recall("Subcutaneous", tp.fn, genes.network.withnames, pc.gene.symbols)
write.csv(plot.sub, "pr_table_sub.csv")

save(plot.thyroid, plot.muscle, plot.lung, plot.blood, plot.sub, file = "fig2.RData")

```

This part generates plots for each figure panel and saves it in a pdf

```{r, echo=FALSE}
### Plots
source("../../src/config")
library(cowplot)

## Read files
theme_set(theme_cowplot(font_size=9)) # reduce default font size

plot.thyroid <- read.csv("pr_table_thyroid.csv", row.names = 1)
plot.thyroid <- plot.thyroid[-which(plot.thyroid$type %in% c("exonic rate","expeff", "gene GC%")),]
plot.thyroid$type <- factor(plot.thyroid$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
plot.thyroid <- ggplot(plot.thyroid, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Thyroid")

plot.lung <- read.csv("pr_table_lung.csv", , row.names = 1)
plot.lung <- plot.lung[-which(plot.lung$type %in% c("exonic rate","expeff", "gene GC%")),]
plot.lung$type <- factor(plot.lung$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
plot.lung <- ggplot(plot.lung, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Lung")

plot.sub <- read.csv("pr_table_sub.csv", row.names = 1)
plot.sub <- plot.sub[-which(plot.sub$type %in% c("exonic rate","expeff", "gene GC%")),]
plot.sub$type <- factor(plot.sub$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
plot.sub <- ggplot(plot.sub, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Adipose - Subcutaneous")

plot.muscle <- read.csv("pr_table_muscle.csv", row.names = 1)
plot.muscle <- plot.muscle[-which(plot.muscle$type %in% c("exonic rate","expeff", "gene GC%")),]
plot.muscle$type <- factor(plot.muscle$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
plot.muscle <- ggplot(plot.muscle, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Muscle - Skeletal")

plot.blood <- read.csv("pr_table_blood.csv", row.names = 1)
plot.blood <- plot.blood[-which(plot.blood$type %in% c("exonic rate","expeff", "gene GC%")),]
plot.blood$type <- factor(plot.blood$type, levels = c("PC corrected","half-PC","quarter-PC", "RIN", "uncorrected"))
plot.blood <- ggplot(plot.blood, aes(x = recall, y = precision, colour = type)) + geom_point(size = 0.3) + 
  xlab("Recall") + ylab("Precision")+ggtitle("Whole Blood")

legend <- get_legend(plot.lung +
  theme(legend.key = element_rect(color = "black", linetype = "solid", size = 0.5),
  legend.key.size = unit(0.3, "cm"), legend.key.height=unit(1.5,"line")) + 
  guides(colour = guide_legend(override.aes = list(size= 1))))

plot_grid(plot.sub + xlim(0,0.16) + ylim(0, 0.35) + theme(legend.position="none"),
  plot.thyroid + xlim(0,0.16) + ylim(0, 0.35) +  theme(legend.position="none"),
  plot.lung + xlim(0,0.16) + ylim(0, 0.35) + theme(legend.position="none"),
  plot.muscle + xlim(0,0.16) + ylim(0, 0.35) + theme(legend.position="none"),
  plot.blood + xlim(0,0.16) + ylim(0, 0.35) + theme(legend.position="none"),
  legend,
  align = 'vh',
           labels = c("a", "b", "c", "d", "e"),
           hjust = -1,
           nrow = 1
           )
```
